// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosInstance, AxiosRequestConfig, AxiosResponse } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError } from "../base";
import { Feedback, FeedbackCreate } from "../models";

/**
 * FeedbackApi - axios parameter creator
 * @export
 */
export const FeedbackApiAxiosParamCreator = function(configuration?: Configuration) {
    return {
        /**
         * Get all feedback on a quiz
         * @param {string} id The ID of a quiz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeedback: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError("id", "Required parameter id was null or undefined when calling getFeedback.");
            }
            const localVarPath = `/quiz/{id}/feedback`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, "https://example.com");
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions: AxiosRequestConfig = { method: "GET", ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Give feedback on a quiz
         * @param {string} id The ID of a quiz
         * @param {FeedbackCreate} [body] Feedback information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        giveFeedback: async (id: string, body?: FeedbackCreate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError("id", "Required parameter id was null or undefined when calling giveFeedback.");
            }
            const localVarPath = `/quiz/{id}/feedback`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, "https://example.com");
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions: AxiosRequestConfig = { method: "POST", ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter["Content-Type"] = "application/json";

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers["Content-Type"] === "application/json";
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    };
};

/**
 * FeedbackApi - functional programming interface
 * @export
 */
export const FeedbackApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get all feedback on a quiz
         * @param {string} id The ID of a quiz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeedback(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Feedback>>>> {
            const localVarAxiosArgs = await FeedbackApiAxiosParamCreator(configuration).getFeedback(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs: AxiosRequestConfig = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Give feedback on a quiz
         * @param {string} id The ID of a quiz
         * @param {FeedbackCreate} [body] Feedback information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async giveFeedback(id: string, body?: FeedbackCreate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await FeedbackApiAxiosParamCreator(configuration).giveFeedback(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs: AxiosRequestConfig = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
    };
};

/**
 * FeedbackApi - factory interface
 * @export
 */
export const FeedbackApiFactory = function(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get all feedback on a quiz
         * @param {string} id The ID of a quiz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeedback(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Feedback>>> {
            return FeedbackApiFp(configuration).getFeedback(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Give feedback on a quiz
         * @param {string} id The ID of a quiz
         * @param {FeedbackCreate} [body] Feedback information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async giveFeedback(id: string, body?: FeedbackCreate, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return FeedbackApiFp(configuration).giveFeedback(id, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FeedbackApi - object-oriented interface
 * @export
 * @class FeedbackApi
 * @extends {BaseAPI}
 */
export class FeedbackApi extends BaseAPI {
    /**
     * Get all feedback on a quiz
     * @param {string} id The ID of a quiz
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbackApi
     */
    public async getFeedback(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Feedback>>> {
        return FeedbackApiFp(this.configuration).getFeedback(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Give feedback on a quiz
     * @param {string} id The ID of a quiz
     * @param {FeedbackCreate} [body] Feedback information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbackApi
     */
    public async giveFeedback(id: string, body?: FeedbackCreate, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
        return FeedbackApiFp(this.configuration).giveFeedback(id, body, options).then((request) => request(this.axios, this.basePath));
    }
}
