openapi: 3.0.3
info:
  title: Kazoot
  description: |-
    An application
  termsOfService: https://kazoot.no/terms-of-service
  contact:
    email: vkbugge@hotmail.com
  license:
    name: MIT License
    url: "https://opensource.org/licenses/MIT"
  version: 1.0.0
servers:
  - url: http://localhost:8080/
  - url: https://api.kazoot.no/
tags:
  - name: User
  - name: User Session
paths:
  /user:
    post:
      tags:
        - User
      description: Register a user (create a user)
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthentication"
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "409":
          description: User already exists
    put:
      tags:
        - User
      description: Update the information of a user
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "409":
          description: User already exists
  /user/{id}:
    get:
      tags:
        - User
      description: Get a specific user
      operationId: fetchUser
      parameters:
        - name: id
          description: The ID of the user
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      tags:
        - User
      description: Delete a specific User
      operationId: deleteUser
      parameters:
        - name: id
          description: The ID of the user
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Successful response
  /user/session:
    post:
      tags:
        - User Session
      description: Log in with credentials
      operationId: login
      requestBody:
        description: Login credentials
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthentication"
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          headers:
            Set-Cookie:
              description: Cookie to be used for authentication.
              schema:
                type: string
                example: "Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE1NzYyMjQxM"
        "401":
          description: Bad credentials
    put:
      tags:
        - User Session
      description: Refresh token
      operationId: refreshToken
      responses:
        "201":
          description: Successful operation
          headers:
            Set-Cookie:
              description: Cookie to be used for authentication.
              schema:
                type: string
                example: "Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE1NzYyMjQxM"
        "401":
          description: Bad credentials
    get:
      tags:
        - User Session
      description: Get logged in user
      operationId: fetchSession
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Bad credentials
    delete:
      tags:
        - User Session
      description: Log out User
      operationId: logout
      responses:
        "204":
          description: Successful operation
components:
  schemas:
    User:
      type: object
      required:
        - username
      properties:
        username:
          type: string
    UserUpdate:
      type: object
      required:
        - username
      properties:
        username:
          type: string
        password:
          type: string
    UserAuthentication:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    Category:
      type: object
      required:
        - name
        - color
      properties:
        name:
          type: string
          maxLength: 32
        color:
          type: string
          minLength: 4
          maxLength: 7
    FeedbackCreate:
      type: object
      required:
        - feedback
      properties:
        feedback:
          type: string
          maxLength: 1024
    Feedback:
      type: object
      required:
        - id
        - quiz_id
        - username
        - feedback
        - created_at
      properties:
        id:
          type: integer
        quiz_id:
          type: string
          format: uuid
        username:
          type: string
        feedback:
          type: string
          maxLength: 1024
        created_at:
          type: string
          format: date-time
    QuestionCreate:
      type: object
      required:
        - type
        - question
      properties:
        type:
          type: string
          enum: ["MULTIPLE", "BOOLEAN", "TEXT"]
        question:
          type: string
          maxLength: 128
    Question:
      type: object
      required:
        - type
        - question
        - correct_answer
      properties:
        id:
          type: integer
        type:
          type: string
          enum: ["MULTIPLE", "BOOLEAN", "TEXT"]
        question:
          type: string
          maxLength: 128
        correct_answer:
          type: string
          maxLength: 128
        media_url:
          type: string
          format: uri
    QuizCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 5
          maxLength: 128
        description:
          type: string
          maxLength: 2000
        difficulty:
          type: integer
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
    QuizOverview:
      type: object
      required:
        - id
        - title
        - description
        - categories
        - creator
        - created_at
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          minLength: 5
          maxLength: 128
        description:
          type: string
          maxLength: 2000
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        creator:
          $ref: "#/components/schemas/User"
        created_at:
          type: string
          format: date-time
    Quiz:
      type: object
      required:
        - id
        - title
        - description
        - categories
        - feedbacks
        - questions
        - creator
        - created_at
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          minLength: 5
          maxLength: 128
        description:
          type: string
          maxLength: 2000
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        feedbacks:
          type: array
          items:
            $ref: "#/components/schemas/Feedback"
        questions:
          type: array
          items:
            $ref: "#/components/schemas/Question"
        creator:
          $ref: "#/components/schemas/User"
        created_at:
          type: string
          format: date-time
