openapi: 3.0.3
info:
  title: Kazoot
  description: |-
    An application
  termsOfService: https://kazoot.no/terms-of-service
  contact:
    email: vkbugge@hotmail.com
  license:
    name: MIT License
    url: "https://opensource.org/licenses/MIT"
  version: 1.0.0
servers:
  - url: http://localhost:8080/
  - url: https://api.kazoot.no/
tags:
  - name: User
  - name: User Session
paths:
  /user:
    post:
      tags:
        - User
      description: Register a user (create a user)
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthentication"
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "409":
          description: User already exists
    put:
      tags:
        - User
      description: Update the information of a user
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "409":
          description: User already exists
  /user/{id}:
    get:
      tags:
        - User
      description: Get a specific user
      operationId: fetchUser
      parameters:
        - name: id
          description: The ID of the user
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      tags:
        - User
      description: Delete a specific User
      operationId: deleteUser
      parameters:
        - name: id
          description: The ID of the user
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Successful response
  /user/session:
    post:
      tags:
        - User Session
      description: Log in with credentials
      operationId: login
      requestBody:
        description: Login credentials
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthentication"
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          headers:
            Set-Cookie:
              description: Cookie to be used for authentication.
              schema:
                type: string
                example: "Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE1NzYyMjQxM"
        "401":
          description: Bad credentials
    put:
      tags:
        - User Session
      description: Refresh token
      operationId: refreshToken
      responses:
        "201":
          description: Successful operation
          headers:
            Set-Cookie:
              description: Cookie to be used for authentication.
              schema:
                type: string
                example: "Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE1NzYyMjQxM"
        "401":
          description: Bad credentials
    get:
      tags:
        - User Session
      description: Get logged in user
      operationId: fetchSession
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Bad credentials
    delete:
      tags:
        - User Session
      description: Log out User
      operationId: logout
      responses:
        "204":
          description: Successful operation
components:
  schemas:
    User:
      type: object
      required:
        - username
      properties:
        username:
          type: string
    UserUpdate:
      type: object
      required:
        - username
      properties:
        username:
          type: string
        password:
          type: string
    UserAuthentication:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
