version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: kazoot
      MYSQL_USER: kazoot
      MYSQL_PASSWORD: kazoot
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - dev

  backend:
    build: ./backend/
    volumes:
      - ./backend:/app
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - dev
    depends_on:
      - mysql

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173
    networks:
      - dev
    depends_on:
      - backend

  mysql_test:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: kazoot_test
      MYSQL_USER: kazoot_test
      MYSQL_PASSWORD: kazoot_test
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - testnet
    profiles:
      - "test"

  test:
    build: ./backend/
    volumes:
      - ./backend:/app
    command: mvn test -Dspring.profiles.active=test
    networks:
      - testnet
    depends_on:
      - mysql_test
    profiles:
      - "test"

networks:
  dev:
    driver: bridge

  testnet:
    driver: bridge

volumes:
  node_modules:
