version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: kazoot
      POSTGRES_USER: kazoot
      POSTGRES_PASSWORD: kazoot
    networks:
      - dev

  backend:
    build: ./backend/
    volumes:
      - ./backend:/app
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - dev
    depends_on:
      - postgres

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173
    networks:
      - dev
    depends_on:
      - backend

  postgres_test:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: kazoot_test
      POSTGRES_USER: kazoot_test
      POSTGRES_PASSWORD: kazoot_test
    networks:
      - testnet
    profiles:
      - "test"

  test:
    build: ./backend/
    volumes:
      - ./backend:/app
    command: mvn test -Dspring.profiles.active=test
    networks:
      - testnet
    depends_on:
      - postgres_test
    profiles:
      - "test"

networks:
  dev:
    driver: bridge

  testnet:
    driver: bridge

volumes:
  node_modules:
