version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./database:/var/lib/postgresql/data

  maven:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
