// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * @type {string}
     * @memberof Category
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Category
     */
    name: string;

    /**
     * @type {string}
     * @memberof Category
     */
    color: string;
}
