// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { QuizAttempt } from './quiz-attempt';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface Competitor
 */
export interface Competitor {

    /**
     * @type {User}
     * @memberof Competitor
     */
    user: User;

    /**
     * @type {QuizAttempt}
     * @memberof Competitor
     */
    attempt: QuizAttempt;
}
