// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Competition } from "./competition";

/**
 *
 *
 * @export
 * @interface PrecompetitionInfo
 */
export interface PrecompetitionInfo {

    /**
     * @type {string}
     * @memberof PrecompetitionInfo
     */
    competitionId: string;

    /**
     * @type {Competition}
     * @memberof PrecompetitionInfo
     */
    competition: Competition;
}
