/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Question } from './question';
 /**
 * 
 *
 * @export
 * @interface QuestionAttempt
 */
export interface QuestionAttempt {

    /**
     * @type {string}
     * @memberof QuestionAttempt
     */
    id: string;

    /**
     * @type {Question}
     * @memberof QuestionAttempt
     */
    question: Question;

    /**
     * @type {string}
     * @memberof QuestionAttempt
     */
    answer: string;

    /**
     * @type {boolean}
     * @memberof QuestionAttempt
     */
    correct: boolean;
}
