// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface QuestionWithAnswer
 */
export interface QuestionWithAnswer {

    /**
     * @type {string}
     * @memberof QuestionWithAnswer
     */
    id: string;

    /**
     * @type {string}
     * @memberof QuestionWithAnswer
     */
    question: string;

    /**
     * @type {string}
     * @memberof QuestionWithAnswer
     */
    answer?: string;

    /**
     * @type {Array<string>}
     * @memberof QuestionWithAnswer
     */
    options?: Array<string>;
}
