// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface Question
 */
export interface Question {
    /**
     * @type {number}
     * @memberof Question
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Question
     */
    type: QuestionTypeEnum;

    /**
     * @type {string}
     * @memberof Question
     */
    question: string;

    /**
     * @type {string}
     * @memberof Question
     */
    correctAnswer: string;

    /**
     * @type {string}
     * @memberof Question
     */
    mediaUrl?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum QuestionTypeEnum {
    MULTIPLE = "MULTIPLE",
    BOOLEAN = "BOOLEAN",
    TEXT = "TEXT",
}
