// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Category } from './category';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface QuizOverview
 */
export interface QuizOverview {

    /**
     * @type {string}
     * @memberof QuizOverview
     */
    id: string;

    /**
     * @type {string}
     * @memberof QuizOverview
     */
    title: string;

    /**
     * @type {string}
     * @memberof QuizOverview
     */
    description: string;

    /**
     * @type {Array<Category>}
     * @memberof QuizOverview
     */
    categories: Array<Category>;

    /**
     * @type {User}
     * @memberof QuizOverview
     */
    creator: User;

    /**
     * @type {Date}
     * @memberof QuizOverview
     */
    createdAt: Date;
}
