// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface QuizAttempt
 */
export interface QuizAttempt {

    /**
     * @type {number}
     * @memberof QuizAttempt
     */
    questionId?: number;

    /**
     * @type {string}
     * @memberof QuizAttempt
     */
    answer?: string;
}
