// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Category } from "./category";
import { Feedback } from "./feedback";
import { Question } from "./question";
import { User } from "./user";
/**
 *
 *
 * @export
 * @interface Quiz
 */
export interface Quiz {
    /**
     * @type {string}
     * @memberof Quiz
     */
    id: string;

    /**
     * @type {string}
     * @memberof Quiz
     */
    title: string;

    /**
     * @type {string}
     * @memberof Quiz
     */
    description: string;

    /**
     * @type {Array<Category>}
     * @memberof Quiz
     */
    categories: Array<Category>;

    /**
     * @type {Array<Feedback>}
     * @memberof Quiz
     */
    feedbacks: Array<Feedback>;

    /**
     * @type {Array<Question>}
     * @memberof Quiz
     */
    questions: Array<Question>;

    /**
     * @type {User}
     * @memberof Quiz
     */
    creator: User;

    /**
     * @type {Date}
     * @memberof Quiz
     */
    createdAt: Date;
}
