// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Kazoot
 * An application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Quiz } from "./quiz";

/**
 *
 *
 * @export
 * @interface Revision
 */
export interface Revision {

    /**
     * @type {string}
     * @memberof Revision
     */
    revisionId?: string;

    /**
     * @type {Quiz}
     * @memberof Revision
     */
    quiz?: Quiz;
}
