/* tslint:disable */
/* eslint-disable */
/**
 * Vet Ikke API.
 * Vet ikke enda...
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserUpdate
 */
export interface UserUpdate {

    /**
     * @type {string}
     * @memberof UserUpdate
     */
    id: string;

    /**
     * @type {string}
     * @memberof UserUpdate
     */
    name: string;

    /**
     * @type {string}
     * @memberof UserUpdate
     */
    email: string;

    /**
     * @type {string}
     * @memberof UserUpdate
     */
    password?: string;
}
